version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 10
    groups:
      # Group minor and patch updates to reduce noise and CI thrash
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
