import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider } from "@/context/sidebar-context";
import { WalletProvider } from "@/context/wallet-context";
import { ToastProvider } from "@/components/ui/toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const clashDisplay = localFont({
  src: "../public/font/clash-display-variable.ttf",
  variable: "--font-clash",
  weight: "500",
  display: "swap",
});

const generalSans = localFont({
  src: "../public/font/general-sans-variable.ttf",
  variable: "--font-general",
  weight: "400",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Stellopay",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/stellopay_icon.png",
    shortcut: "/logos/stellopay_icon.png",
    apple: "/logos/stellopay_icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${clashDisplay.variable} ${generalSans.variable} antialiased`}
      >
        <SidebarProvider>
          <WalletProvider>
            <ToastProvider>{children}</ToastProvider>
          </WalletProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
